### ISSUE TITLE
Daily gridline not aligned with header

### ISSUE THREAD

**Issue by dflaven** [jsGanttImproved/jsgantt-improved#153]
In the **daily** view mode, the task grid is slightly misaligned with the header grid. This becomes significant after a few weeks.

On the screenshot below you can see that the grey columns showing the weekends are not aligned with the header.

**To Reproduce**
1. Go to  the online demo https://jsganttimproved.github.io/jsgantt-improved/
2. Switch to "days" mode
3. Scroll the right part of the chart completely to the right 

**Expected behavior**
The grid line should be aligned with the header.

**Screenshots**
![image](https://user-images.githubusercontent.com/2705690/53251386-cea23800-36bc-11e9-905e-4e661450c559.png)

**Desktop:**
 - OS: Windows 7 Pro
 - Browser [FireFox 65, Chrome 72]

**Potentiel fix:**
I found that increasing the width of the 'gtaskcell' by 2 pixels seem to fix the issue (notice the +2 at line 677):
```javascript
                if (this.vFormat == 'day') {
                    if (vTmpDate.getDay() % 6 == 0) {
                        vHeaderCellClass += 'wkend';
                        vCellClass += 'wkend';
                    }
                    if (vTmpDate <= vMaxDate) {
                        vTmpCell = this.newNode(vTmpRow, 'td', null, vHeaderCellClass);
                        this.newNode(vTmpCell, 'div', null, null, utils_1.formatDateStr(vTmpDate, this.vDayMinorDateDisplayFormat, this.vLangs[this.vLang]), vColWidth+2);
                        vNumCols++;
                    }
                    vTmpDate.setDate(vTmpDate.getDate() + 1);
                }
``` 
but I have no idea why 2 pixels more are required (a matter of cell borders ??)

Hope this helps.

**Comment by mariohmol** [comment]
Thanks!! can u send a PR?

**Comment by dflaven** [comment]
Ok, I'll make the early PR next week. I'm just a bit uncomfortable for not understanding the root cause...
Cheers.

**Comment by mariohmol** [comment]
i know what u mean.. i fixed some issues using this spacing as well.. hard to know

**Comment by dflaven** [comment]
Never mind, I did a test on the develop branch and it looks like the issue was already fixed by the same fix as for Issue #139

Thanks a lot for the assistance anyway and congratulations for this very nice work.

**Comment by mariohmol** [comment]
thanks!

**Comment by dflaven** [comment]
Actually it worked on the demo, but not with my sample data... the header is still not aligned with the grid. I'm preparing a fix as a pull request... stay tuned.

**Comment by mariohmol** [comment]
welcome mate.. lets help cause this project is awesome!

**Comment by mariohmol** [comment]
fixed on jsgantt-improved@2.1.8

**Comment by mut88** [comment]
It still looks like this isn't correct in Chrome.

Chrome Version 76.0.3809.100 (Official Build) (64-bit)
![image](https://user-images.githubusercontent.com/53948155/62841465-f6d32280-bc6d-11e9-8588-2bebe7636581.png)

It is currently 11 August and ~7:30 PM at my local time.

It looks like the current day is 16 August and the bar for the tool tip that I've highlighted is 11 August and not 06 August.

I also have the MS Edge Browser and the dates appear correct in that.

IE 11 does not render the gantt chart for me so I cannot see if it is correct or not.

Regards,
Jim

**Comment by mariohmol** [comment]
Thanks!

Can u provide a json with this data?

**Comment by mut88** [comment]
Here it is.  

Thank you for all the work you are putting into this!  

[jsonfile.zip](https://github.com/jsGanttImproved/jsgantt-improved/files/3490639/jsonfile.zip)
