### ISSUE TITLE
End Date Incorrect

### ISSUE THREAD

**Issue by jitu7046** [jsGanttImproved/jsgantt-improved#48]
Everything is working fine. But If I set the pGroup as 1, then some endDates it's not showing correctly. Instead it shows current date.
I am setting the endDate as required format like yyyy-mm-dd(e.g. 2017-03-30).
But it is showing current date as today is 01/09/2017.
If I am changing the pGroup value to 0, It's working fine. But I need to have pGroup as 1 since it is having some sub-tasks.

**Comment by thclark** [comment]
I have the same value with start dates, which I'm parsing out of a text editor then placing into here. Some of them worked, some didn't. I copied and pasted in my editor, which seemed to change whether they worked, leading me to believe this might be an issue with unescaped characters or whitespace.

The only test case I have is in constant flux, but if I manage to reliably recreate this I'll post something. I'll also try out the pGroup changes that @jitu7046 mentions.

**Comment by thclark** [comment]
OK I've isolated a case showing this problem occurring, it's due to the start date selection.

### Red herring: whitespace and escaped characters

Further to my previous, I investigated with both raw string and unicode encodings of strings, and did various cross encodings to show any hidden literals in my strings.

**Conclusion:** This is **not** to do with string encoding or whitespacing. I can reproduce with both raw and unicode and with a strictly defined string in my IDE.

### Date ranges

I accidentally realised this was due to the date range set. It's presumably something to do with the grouping, maybe a backward check that a task must fall within a group's date range?

In the test case below, you'll notice that in the first WP, the correct start date is after today's date (12th Sep 2017), whilst the second task's correct start date has already passed.

The second task is displaying correctly, whist the first, whose start date is after today, is not.


```html

<div class="row justify-content-md-center">
   <div style="position:relative" class="gantt" id="GanttChartDIV"></div>
   <script type="text/javascript">
   var g = new JSGantt.GanttChart(document.getElementById('GanttChartDIV'), 'month');
   g.setCaptionType('Complete');  // Set to Show Caption (None,Caption,Resource,Duration,Complete)
   g.setQuarterColWidth(24);
   g.setDateTaskDisplayFormat('day dd month yyyy'); // Shown in tool tip box
   g.setDayMajorDateDisplayFormat('mon yyyy - Week ww'); // Set format to display dates in the "Major" header of the "Day" view
   g.setWeekMinorDateDisplayFormat('dd mon'); // Set format to display dates in the "Minor" header of the "Week" view
   g.setShowTaskInfoLink(1); //Show link in tool tip (0/1)
   g.setShowEndWeekDate(0); // Show/Hide the date for the last day of the week in header for daily view (1/0)
   g.setUseSingleCell(1); // Use one cell per table row.  Helps with rendering performance for large charts.
   g.setUseSingleCell(10000); // Set the threshold at which we will only use one cell per table row (0 disables).  Helps with rendering performance for large charts.
   g.setFormatArr('Day', 'Week', 'Month', 'Quarter'); // Even with setUseSingleCell using Hour format on such a large chart can cause issues in some browsers
   g.setShowRes(0);// Stops the resource column showing. VIew it in the tooltips
   g.setUseSort(0);// Stops the super weird non-obvious sorting and displays in the order created
   g.setShowStartDate(1);
   g.setDateInputFormat('yyyy-mm-dd')
   var data = JSON.parse('[{"abbrev_name": "WP1.1 Project initiation", "dependencies": [[6, 3], [6, 2], [6, 1], [4, 1], [3, 1], [2, 6], [2, 1], [1, 3], [1, 2]], "dependency_ids": [25, 24, 23, 13, 10, 9, 4, 3, 2], "display_as_group": 1, "effort": [], "end_date": "2018-03-01", "id": 1, "is_milestone": 0, "jsgantt_class": "gtaskgreen", "name": "WP1.1 Project initiation", "name_text": "Project initiation", "package": [1, 1], "parent_task_id": 0, "percent_complete": 0, "predecessor_ids": [], "predecessors": [[]], "resource_str": "-", "start_date": "2018-01-01", "text": "Project initiation", "url": "https://github.com/oasysapp/project-cleo/issues/1"}, {"abbrev_name": "WP1.2 Quarterly Reporti...", "dependencies": [], "dependency_ids": [], "display_as_group": 1, "effort": [["@thclark", 10], ["@ncpearson", 24]], "end_date": "2019-12-31", "id": 2, "is_milestone": 0, "jsgantt_class": "gtaskgreen", "name": "WP1.2 Quarterly Reporting and Review Meetings", "name_text": "Quarterly Reporting and Review Meetings", "package": [1, 2], "parent_task_id": 0, "percent_complete": 0, "predecessor_ids": [1], "predecessors": [[1, 1], [1, 1]], "resource_str": " [@thclark:10 @ncpearson:24]", "start_date": "2016-03-01", "text": "Quarterly Reporting and Review Meetings", "url": "https://github.com/oasysapp/project-cleo/issues/2"}]');
   console.log(data)
   var arrayLength = data.length;
   for (var i = 0; i < arrayLength; i++) {
   var wp = data[i];
   console.log(wp)
   g.AddTaskItem(new JSGantt.TaskItem(wp.id, wp.abbrev_name, wp.start_date, wp.end_date, wp.jsgantt_class,  wp.url, wp.is_milestone, wp.resource_str,   wp.percent_complete,   wp.display_as_group, wp.parent_task_id,  1, wp.predecessor_ids,      '',      wp.text, g));
   }
   g.Draw()
   </script>
    
   </div>
```

I hope this helps. Apologies if I've misunderstood usage, leading to this error!

**Comment by mariohmol** [comment]
We had some fixes regarding this and maybe its fixed now.. can u please retest?

please provide a working example using this as start point?

https://codepen.io/mariomol/pen/mQzBPV

feel free to reopen

**Comment by pozo123** [comment]
I am having a similar issue. Whenever the start date of subtasks is after the current date, the entire task's start date is displayed as the current date.
When the end date of a subtask is after the current date, sometimes it displays as the current date, but sometimes it doesn't and it shows the proper dates.
I can't reproduce the example with the codepen you provided cause I'd need to change the dates from the json to some after the current date. 
My example is using data retrieved from firebase, but if you need it I could make one with hardcoded tasks.

**Comment by pozo123** [comment]
![screen shot 2019-03-06 at 11 43 59 am](https://user-images.githubusercontent.com/21698693/53901759-4fd6c480-4005-11e9-8847-8715f76e9b93.png)

**Comment by pozo123** [comment]
That's a screenshot of my example. None of the dates that fall on the current date line are supposed to, so the three from above display a wrong end date and the five from the bottom have a wrong start date. The rest of the dates seem to be working correctly, so it looks the issue is only presented when BOTH the start and end date are either before or after the current date.

**Comment by wmunsell** [comment]
i know this issue has been marked as closed, but (unless i'm doing something wrong) it still appears to be an issue. even though i am specifying both a pStart and pEnd date, the end date is displaying as today's date. am i the only one still experiencing this issue? 
![EndDate](https://user-images.githubusercontent.com/12951311/66061102-c17be000-e50c-11e9-8b46-be62c8ec1f6c.JPG)

**Comment by jortorri** [comment]
Hello. I've the same problem, this issue shoudn't be closed!

**Comment by teapack666** [comment]
Anything new on this issue ? 
I have the exact same problem and don't know how to solve it...

**Comment by wightman-gis** [comment]
> Anything new on this issue ?
> I have the exact same problem and don't know how to solve it...

the only thing that i could suggest is to format your dates like this 
```
"pStart": "2018-03-01 00:00",
"pEnd": "2019-05-15 00:00",
"pPlanStart": "2018-03-01 00:00",
"pPlanEnd": "2019-05-15 00:00",
"pClass": "ggroupblack",
```
this is the only thing that i found to work for me.

**Comment by mariohmol** [comment]
@wightman-gis you are saying that you have to have plan and normal dates with same value?

in this case you can just omit plan dates...

**Comment by wightman-gis** [comment]
@mariohmol no. im saying that in order for me to get the dates to work correctly i have to place this into yyyy-mm-dd hh:mm format.

**Comment by 3AUCE** [comment]
any updates on this?

**Comment by nidu** [comment]
@3AUCE is it happening with the latest version? Could you please provide some minimal data set to reproduce the problem?

**Comment by psycohomer** [comment]
Any update as this is still happening. 
Parent:
array (
    'pLink' => 'XXXXX.com/ID-420',
    'pID' => '420',
    'pName' => 'MTO Toolset',
    'status' => 'In Development',
    'pStart' => '2019-02-14 00:00',
    'pEnd' => '2019-10-28 23:59',
    'pPlanStart' => '',
    'pPlanEnd' => '',
    'pComp' => 25,
    'pClass' => 'ggroupblack',
    'pParent' => 0,
    'pOpen' => 0,
    'pGroup' => 1,
    'pRes' => 'XXXXXX',
    'pBarText' => 'ID-420',
  ),
Child: 
array (
    'pLink' => 'https://XXXXXXX.com/ID-442',
    'pID' => '442',
    'pName' => 'Migrate to OAuth2',
    'status' => 'To Do',
    'pStart' => '2019-02-14 00:00',
    'pEnd' => '2019-10-28 23:59',
    'pPlanStart' => '',
    'pPlanEnd' => '',
    'pClass' => 'gtaskblue',
    'pParent' => '420',
    'pOpen' => 1,
    'pGroup' => 1,
    'pRes' => NULL,
    'pBarText' => 'ID-442',
  ),
Screen shot showing the parent is defaulting to todays date
![Screen Shot 2020-04-07 at 1 03 50 PM](https://user-images.githubusercontent.com/17458472/78703749-5d2d4500-78d0-11ea-9491-0c00d46a1cd5.png)

**Comment by ankh2009** [comment]
I was able to reproduce this issue.
It is appeared in 2 cases:
1. If 2 tasks share same Pid
2. If Some subtask has empty Start Date and End Date

**Comment by mariohmol** [comment]
Thanks @ankh2009 !!

Maybe we can do something that checks the pID and if any is duplicated we send a console.warn?

**Comment by mariohmol** [comment]
## Status: Fixed in current code

After reviewing the current codebase, the end-date-showing-as-today bug described here has been resolved.

### What was causing it

Two root causes were identified over the lifetime of this issue:

1. **Group date calculation didn't honour the parent's explicitly set dates** — fixed in commits `710ff11` and `fd885c8` ("Honour dates on standard group tasks if they fall outside of the calculated range").

2. **Duplicate `pID` values** (identified by @alex-epifanov in April 2020) — if two tasks share the same `pID`, the parent-child lookup in `processRows` breaks and dates get miscalculated. Each task must have a unique `pID`.

### Current code is correct

`processRows` in `src/task.ts` now uses `getEndVar()` (returns the raw `vEnd` field) when accumulating children's max dates, so the `new Date()` fallback in `getEnd()` never contaminates group date calculations. The parent's own originally-set end date is preserved in `vGroupMinEnd` and used as a lower bound.

### If you are still seeing this

- Verify every task has a unique `pID`.
- If a subtask has an empty `pStart`/`pEnd`, that's fine — it is skipped correctly.
- If you can still reproduce it with unique IDs and the latest release, please open a new issue with a minimal reproducible example (a [CodePen](https://codepen.io) or similar).

Closing as fixed.
